title: Peter Lovett
email: pelovett(at)gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi,
  I'm currently a PhD Student at the University  of
  Arizona studying natural language processing, and
  machine learning more braodly. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pelovett.github.io"
logo: "https://avatars1.githubusercontent.com/u/21147496?s=460&v=4"
show_downloads: false
twitter_username: petermlovett
github_username:  pelovett
is_project_page: false
google_analytics: false
# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
